### ISSUE TITLE
Not working on Web

### ISSUE THREAD

**Issue by heymind** [supernovel/flutter_web_fonts#1]
I have found that there may be a bug.

https://github.com/supernovel/flutter_web_fonts/blob/b4a2b2b11bda51193314521a5cbde9e16c1030aa/lib/fonts/web_fonts_base.dart#L139

Here we call `file_io.loadFontFromDeviceFileSystem` to load a font's bytes data. We fallback to fetch from the network if founds any exception. But the case just returns `null` without exception will cause `_loadFontByteData` returning `null` without trying the network.

https://github.com/supernovel/flutter_web_fonts/blob/b4a2b2b11bda51193314521a5cbde9e16c1030aa/lib/fonts/file_io.dart#L17

Here is an easy fix here and tested. I will make a PR if you wish.

https://github.com/heymind/flutter_web_fonts/blob/f31aabc27ded97700b0bcb9f88e9919702520bdc/lib/fonts/web_fonts_base.dart#L139

**Comment by supernovel** [comment]
Sorry for delay. If you make a PR, I'll check it out. thank you.
